### ISSUE TITLE
Atmos incoherence display?

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#1102]
Shouldn't it be 15 dynamic ojects and 1 Bed channel?
```
Audio
Format                                   : MLP FBA 16-ch
Format/Info                              : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name                          : Dolby TrueHD with Dolby Atmos
Bit rate mode                            : Variable
Maximum bit rate                         : 7 662 kb/s
Channel(s)                               : 8 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb
Sampling rate                            : 48.0 kHz
Frame rate                               : 1 200.000 FPS (40 SPF)
Number of dynamic objects                : 11
Bed channel count                        : 1 channel
Bed channel configuration                : LFE
```

**Comment by Sami32** [comment]
Hum, i didn't saw it but frame rate seem wrong.

**Comment by Sami32** [comment]
https://ufile.io/q3vbi    (lien valide 30 jours)

**Comment by ValZapod** [comment]
@Sami32 Place file in google drive. Really((

**Comment by Sami32** [comment]
I apology for the link, for my defense it was my first time use and i wasn't aware that they will do that.
No way, i'm not a fan of Google...

Here a new link:
http://samples.ffmpeg.org/ffmpeg-bugs/trac/ticket4490/6zc.thd

**Comment by ValZapod** [comment]
@Sami32 Well, just today I saw "ant man and the wasp" from torrents and here is MLF Atmos. I have maybe 20 films with THD dolby atmos and all of them have that value. So...
```
Audio #3
ID                          : 4
Format                      : MLP FBA 16-ch
Format/Info                 : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name             : Dolby TrueHD with Dolby Atmos
Codec ID                    : A_TRUEHD
Duration                    : 1 h 58 min
Bit rate mode               : Variable
Bit rate                    : 4 746 kb/s
Maximum bit rate            : 7 335 kb/s
Channel(s)                  : 8 channels
Channel layout              : L R C LFE Ls Rs Lb Rb
Sampling rate               : 48.0 kHz
Frame rate                  : 1 200.000 FPS (40 SPF)
Compression mode            : Lossless
Stream size                 : 3.92 GiB (9%)
Language                    : English
Default                     : No
Forced                      : No
Number of dynamic objects   : 13
Bed channel count           : 1 channel
Bed channel configuration   : LFE
```

**Comment by Sami32** [comment]
Same wrong frame rate but different number of dynamic objects.
Thanks for your sharing +1

**Comment by ValZapod** [comment]
So, this is not a bug. 16 bit channel presentation is just a flag, it does not mean it is 16 channels inside. Atmos for home only supports 16 channels max, here it is ONLY LFE (not other 7 channels) that is bed. Others up to 15 are dynamic objects, some of the "dynamic" objects may be just 7 channels static. There is also a way to unify some different objects together.

**Comment by ValZapod** [comment]
> Same wrong frame rate

Actually frame rate is correct here. It is indeed 1200 fps. Every frame in TrueHD is 1/1200 seconds on Blu-ray and has 40 samples.

**Comment by ValZapod** [comment]
Here fps is wrong, but 16 channels with 15 dynamic objects and 1 LFE bed (this is from Dolby Vision March 2018 demo disk): 
```
Audio #1
ID                          : 4352 (0x1100)
Menu ID                     : 1 (0x1)
Format                      : MLP FBA AC-3 16-ch
Format/Info                 : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name             : Dolby TrueHD with Dolby Atmos
Muxing mode                 : Stream extension
Codec ID                    : 131
Duration                    : 2 min 54 s
Bit rate mode               : Variable
Bit rate                    : 640 kb/s
Maximum bit rate            : 7 563 kb/s
Channel(s)                  : 8 channels
Channel layout              : L R C LFE Ls Rs Lb Rb
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Compression mode            : Lossless
Stream size                 : 13.3 MiB (0%)
Service kind                : Complete Main
Number of dynamic objects   : 15
Bed channel count           : 1 channel
Bed channel configuration   : LFE
```
same about EAC3 Atmos:
```
Audio #2
ID                          : 4353 (0x1101)
Menu ID                     : 1 (0x1)
Format                      : E-AC-3 JOC
Format/Info                 : Enhanced AC-3 with Joint Object Coding
Commercial name             : Dolby Digital Plus with Dolby Atmos
Format profile              : Blu-ray Disc
Format settings             : Dolby Surround EX
Muxing mode                 : Stream extension
Codec ID                    : 132
Duration                    : 2 min 54 s
Bit rate mode               : Constant
Bit rate                    : 1 664 kb/s
Channel(s)                  : 8 channels
Channel layout              : L R C LFE Ls Rs Lb Rb
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Compression mode            : Lossy
Stream size                 : 34.7 MiB (0%)
Service kind                : Complete Main
Complexity index            : 16
Number of dynamic objects   : 15
Bed channel count           : 1 channel
Bed channel configuration   : LFE

```

You can check how many channels are possible in this video (17 channels is just a bug in that analyser, since that is what complexity 16 does to you):

https://youtu.be/CBqWYrOMxcY?t=469

**Comment by JeromeMartinez** [comment]
> Here fps is wrong

Why wrong? AFAIK  MLP FBA (TrueHD) is 1 200 fps. I put the smallest value when E-AC-3 and MLP FBA are interleaved, do you mean that you would like both (from  E-AC-3 and MLP FB, e.g. "1200 / 31.250")?

**Comment by ValZapod** [comment]
> AFAIK MLP FBA (TrueHD) is 1 200 fps

That is what I said. BTW, not all samples are 1200, some are 1 102.5, for example: https://www.filedropper.com/samplethd

> I put the smallest value when E-AC-3 and MLP FBA are interleaved

Oh. Okay. You mean from AC3? AC3 is interleaved with TrueHD? Or you mean really EAC3 (that ac3 is a core of, that needed to be decoded to decode E-AC3)?

> that you would like both

I would like to have 1200 there, of course...

P.S. Is that true that TrueHD is always 24 bit and just can have some bytes zeroed out? https://forum.doom9.org/showpost.php?p=1078061&postcount=2102

**Comment by JeromeMartinez** [comment]
>  not all samples are 1200, some are 1 102.5, 

1200 for 48 kHz, else it is adapted, right.

> You mean from AC3? 

Typo, I mean AC-3.

> I would like to have 1200 there, of course... 

I'll think about how to display that, but not soon... Very long term about how to display such complex (several pieces of same metadata) info.

> Is that true that TrueHD is always 24 bit and just can have some bytes zeroed out?

True. MLP FBB (original MLP) has metadata for 16/20/24 bits, MLP FBA (TrueHD) does not have it. I guess I need to write "24 bits" in MediaInfo for TrueHD (with the complexity that with AC-3 interleaved the bitdepth is for TrueHD and nothing for AC-3 because AC-3 has a "dynamic" bitdepth).

**Comment by ValZapod** [comment]
The key problem in MLP encoder that was losing 16 frames was fixed just now in https://github.com/FFmpeg/FFmpeg/commit/9f420163c6207b9c54badd30056974a6b3450bfd
shorten_by is also implemented (for 1/1200 perfect size if it is less that 1/1200, I suppose)

So the encoder no longer is experemental IMHO.

Next commit can I suppose fix https://github.com/mifi/lossless-cut/issues/771#issuecomment-869794815 https://github.com/FFmpeg/FFmpeg/commit/034133a0df5f327aba36ee25db9452cda9e1a62b

Decoding with -acodec pcm_s24le (and even decoding of Dolby Media Encoder Standalone Edition https://trac.ffmpeg.org/ticket/5054) is somehow still broken even though you say it is always 24 bit anyway. There is still a problem with mono vs stereo, but that is just cosmetic issue, since the internal decoder still goes to mono: https://trac.ffmpeg.org/ticket/1726
