### ISSUE TITLE
Is this MPEG Audio really dual mono; why code commented??

### ISSUE THREAD

**Issue by ValZapod** [MediaArea/MediaInfoLib#1323]
https://github.com/MediaArea/MediaInfoLib/blob/5971e33598884f43eee55e2c338bbf9aab32663f/Source/MediaInfo/Audio/File_Mpega.cpp#L1549

Why this code is commented? I have a file and opened some issues https://trac.videolan.org/vlc/ticket/22392

The files is here https://trac.videolan.org/vlc/attachment/ticket/22392/dest.mka is it dual mono? If yes, why ffmpeg says it is stereo? I am so confused. And dual mono somehow in VLC plays only one channel in 2.0 channels.

Some reference that you still need to play dual mono in two different channels https://sound.stackexchange.com/questions/35545/if-a-track-contains-two-channels-is-the-track-stereo
https://sound.stackexchange.com/questions/25228/0db-mono-vs-0db-stereo

**Comment by JeromeMartinez** [comment]
> Why this code is commented? 

For the reason indicated in the comment you cited. If someone is interested in improving this code, I may take it.
Generally speaking, please 1 issue per issue ticket.

> The files is here https://trac.videolan.org/vlc/attachment/ticket/22392/dest.mka is it dual mono?

As indicated, yes.
Something I should do 1 day is to show 2 tracks in MediaInfo for such content, as I do for another format having several contents in 1 stream (namely Dolby E), it is actually 2 tracks coded in the same stream.

>  If yes, why ffmpeg says it is stereo?

FFmpeg does not handle well dual mono, and don't do the difference between "L R" (Left + Right channels) and dual mono ("M M" style), "stereo" here means 2 channels, not that the 2 channels are "L R".

Note that MediaInfo does not show "L R" channel layout from your file, there is a reason (it is not "L R").

> And dual mono somehow in VLC plays only one channel in 2.0 channels.

And they do correctly, VLC does the correct job: playing back only the first mono track by default, having the 2 mono tracks played by default would be ugly to hear. 1 criticism could be that they should show Mono 1 then Mono 2 when you select the channel in "Stereo mode" (bad name too) instead of misleading "Left" and "Right".

If a player plays both contents at the same time by default, this is a bug from this player, you should open an issue ticket on its issue tracker.

An addition, about your comment in VLC tracker:

> FFplay of FFmpeg thinks that it is stereo. And it IS stereo. What we are arguing about? 

They didn't argue that it is not a 2-channel stream. They indicated that you imagine that "2 channel" (or "stereo" in FFmpeg) always mean "L R", this is usually the case but no always. In the case of this file, it is 2-channel dual mono content.

Closing, as it is not a MediaInfo issue (and we don't use the word "stereo"), but an issue about understanding the difference between "L R" (Left + Right, same content to be played at the same time) and "M M" (dual mono, 2 actual content, not to be played at the same time).
