### ISSUE TITLE
Delay in milliseconds in BWF doesn't capture sample accuracy of TimeReference in BWF

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfoLib#1876]
The "Delay" field only has millisecond accurate so it loses precision from the sample count in the BWF.

E.g. for a BWF with a sample rate of 48000 and a TimeReference of 168005838, which is 3500.121625 seconds, BWF MetaEdit shows a translated time of 00:58:20.121 (168005808 samples) and MediaInfo shows a Delay of 00:58:20.122 (168005856 samples).

Should there be a "Delay_Samples" or equivalent to preserve the precision?

**Comment by JeromeMartinez** [comment]
@plondino difference is due to `bext` being before `fmt ` in your file, and we forgot 🙈 to put more precision in that case (usually `fmt ` is after `bext` and we have 2 pieces of code for that depending on where we have needed information, TimeReference and frequency).
[patch on the way](https://github.com/MediaArea/MediaInfoLib/pull/1877), but unfortunately not in v23.10, it will be in the version after.
