### ISSUE TITLE
Add a Travis CI test for CMake compilation

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaInfoLib#193]

**Comment by tribouille** [comment]
Not possible right now:

The CMakeLists.txt requires a cmake version >= 2.8.11 and the version on (Github)Travis is 2.8.7
https://travis-ci.org/tribouille/MediaInfoLib/builds/137743215#L1279

If I ask for a require level a 2.8.7, some macros are not defined:
https://travis-ci.org/tribouille/MediaInfoLib/builds/137745213#L1279

**Comment by drizt** [comment]
Hi, I can't reply to email. My e-mail server refuses me. So I write answer here.

It is ok to use include_directories instead of  target_include_directories 
only one case when PRIVATE keyword is implied.
But there is target_include_directories with INTERFACE keyword. INTERFACE 
means that this folder wont be used on build stage but path to this folder 
will be added to generated CMake config (find) module. So your app which 
requires MediaInfo can't find headers and you (probably) will get compilation 
error.

**Comment by drizt** [comment]
Also it is possible to use trusty (14.04) instead of precise (12.04). Trusty has cmake 2.8.12.

**Comment by JeromeMartinez** [comment]
> So I write answer here.

That's fine, actually I prefer public conversation :).

> So your app which requires MediaInfo can't find headers and you (probably) will get compilation error.

I wonder how it was done before CMake 2.8.11.

> Also it is possible to use trusty (14.04) instead of precise (12.04). Trusty has cmake 2.8.12.

Right, this is another solution, I was hesitation between both solutions and I like to support old platforms when I can.
Maybe it is too difficult here and we can try to switch to Ubutnu 14.04.

**Comment by drizt** [comment]
> I wonder how it was done before CMake 2.8.11.

It was not. CMakePackageConfigHelpers was introduced only in CMake 2.8.8. So if need to support CMake 2.8.7 need to make big changes in CMake script.

**Comment by JeromeMartinez** [comment]
OK, so we don't try to support Ubuntu 12.04 and we switch to Ubuntu 14.04.

**Comment by g-maxime** [comment]
https://github.com/MediaArea/MediaInfoLib/commit/f23ab427c28e1b0cbc9b05053f32181a40ee156e
