### ISSUE TITLE
MediaInfo displays "Progressive" for  MXF/JPEG2000 with SMPTE 422 I2 wrapping mode

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfoLib#2037]
Mediainfo displays "Progressive" for **Scan type** for an JPEG 2000 in an MXF wrapped with the I2 wrapping mode.  The 
default is "Frame Undefined" (06 0E 2B 34 04 01 01 07 0D 01 03 01 02 0C 01 00) where the frame structure was not specified in the standard. ST 422:2013 defined new wrapping modes, including explicit interlaced modes.  

I2 wrapping mode (06 0E 2B 34 04 01 01 0D 0D 01 03 01 02 0C 04 00) has the below frame structure:

<img width="881" alt="Screen Shot 2022-09-13 at 10 12 10 AM" src="https://user-images.githubusercontent.com/40502255/190054666-4024dd06-4940-4066-839d-63eb05d5818f.png">

<img width="999" alt="Screen Shot 2022-09-13 at 10 12 45 AM" src="https://user-images.githubusercontent.com/40502255/190052551-2aaf674a-4c54-4d64-8ad9-2acf2d65fd05.png">

MediaInfo should read this as interlaced.  I can provide a sample file.

**Comment by JeromeMartinez** [comment]
@plondino,

> You're correct, the file I sent should have had the StoredHeight of FULL_FRAME. I will send you an update file which is correct*.

Does this mean that such file is actually created by tools not in production? 
While fixing the issue with your file which meets ST 422-2019 I2 spec, I noticed that none of the files I have from different producers, including [Library of Congress RDD 48 MXF Golden files](https://www.digitizationguidelines.gov/guidelines/MXF_app_sampleFiles.html) (cc @kmurmur), are conform to the specification about FrameLayout for I2 files, and I had to implement several exceptions in my code for handling that because all other formats (DV, MPEG-2 Video...) use MXF FrameLayout SEPARATE_FIELDS even if both fields are stored in the same MXF frame, for JPEG 2000 MXF FrameLayout becomes a store method tip rather than a field temporality tip.

Anyway, it was more complicated than what I anticipated because of all the "non conforming" (which seem to be the vast majority of) files in the wild so I had to handle several cases (UL with essence container label Content Kind of 0 or 4 for the same content kind, FrameLayout of FULL_FRAME or SEPARATE_FIELDS  for the same content kind, ...) by probing the JPEG 2000 codestream directly in some cases, [development snapshots](https://mediaarea.net/download/snapshots/binary/) include the fix.

**Comment by kmurmur** [comment]
Thanks for the tip @JeromeMartinez and glad to hear you are using the LC sample files @plondino. I'll look into this issue - I think some of the 'golden' files turned out to have non-conforming issues after all. I have new sample files to add to the batch and I'll ping you when they are up.
