### ISSUE TITLE
Differences in the Channel Layout for certain cases

### ISSUE THREAD

**Issue by nsaadi** [MediaArea/MediaInfoLib#2062]
Mediainfo v23.4
We have differences in the Channel Layout for certain cases, for exemple when we use ffmpeg and Sencore  they are agree on a **Channel Configuration layout: mono (C)**, and previously with mediainfo we had the value "C", which was fine.
However, now mediainfo returns "M", which means mono but in the sense of: **not multi-channel**.

What can we understand from this new change? We think it's a regression. Is it possible to look into this issue and give us a quick response, please?

Best regards

**Comment by JeromeMartinez** [comment]
> What can we understand from this new change?

We try to do the difference between M (Mono = not multi-channel, or without indicated position) and C (Center = there is a position explicitly indicated).

If you think that the content indicates C rather than M, please share a sample file or at least a MediaInfo report.

> We think it's a regression.

Why? And how does it impact you? Difficult to map M to C in your workflow?

> Is it possible to look into this issue and give us a quick response, please?

Note that a SLA is not included in the free support so there is no commitment on any answer here, if you need a SLA [we provide it](https://mediaarea.net/Services), don't hesitate to [contact us](https://mediaarea.net/Contact) for details.

**Comment by nsaadi** [comment]
Here sample: Whit mediainfo 21.09
![image](https://github.com/MediaArea/MediaInfoLib/assets/51754417/a894a959-f493-4f9b-bf26-d903a5d765e2)
Mediainfo latest
![image](https://github.com/MediaArea/MediaInfoLib/assets/51754417/c91e8d06-6fab-42fe-95f1-8e1e45e03d24)
[audio_channel.zip](https://github.com/user-attachments/files/15973327/audio_channel.zip)

**Comment by JeromeMartinez** [comment]
As said in the previous message, it is wanted, our current policy for all formats is to handle 1-channel content as "mono" except when the format makes an explicit difference between M and C.
what is the issue with handling "M" there? Isn't it a mono-channel content? If not, where are the other channels?

**Comment by nsaadi** [comment]
Hello
For this change, we can adapt. You can close this ticket.
Thx
