### ISSUE TITLE
Mismatch between "Delay" and "Start Timecode" in 23.98 NDF audio only MXF

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfoLib#2110]
I have a frame wrapped MXF file with an MXF timecode track.  The start timecode is `00:59:20:00` at `24000/1001`, which is 85440 frames which at 24000/1001 is 3563.56 seconds, or 0:59:23.560000 in hh:mm:ss:ms format.
```
      <FrameRate_Num>24000</FrameRate_Num>      
      <FrameRate_Den>1001</FrameRate_Den>      
      <TimeCode_FirstFrame>00:59:20:00</TimeCode_FirstFrame>      
```
However, the delay section appears to miscalculate the seconds value as:
```
      <Delay>3560.000</Delay>      
      <Delay_String1>59 min 20 s 0 ms</Delay_String1>    
```
If you convert that seconds value into a 24000/1001 timecode, you get `00:59:16:11` or 85355 frames.  Shouldn't the delay value in seconds match the start timecode in the MXF timecode track?

Attached is full MediaInfo XML, sample files available on request.

[Warner_Media_OTT_4220517_ALL_AMERICAN_HOMECOMING_YR03_23_24_E3457944_23976fps_SPANISH_LATIN_5_1_3360070_1_10_audio_12855909.xml.txt](https://github.com/user-attachments/files/17030189/Warner_Media_OTT_4220517_ALL_AMERICAN_HOMECOMING_YR03_23_24_E3457944_23976fps_SPANISH_LATIN_5_1_3360070_1_10_audio_12855909.xml.txt)

**Comment by JeromeMartinez** [comment]
@plondino should be OK now with latest snapshot.
Note that `Delay` here is there for legacy reasons but it is not the best thing to use because it is based on a timecode and displayed as a timestamp. But no plan to remove it.
For MXF Clip Audio, Edit rate of the time code is sometimes the audio frequency e.g. 48000, in that case I check the edit rate of the master DCP or IMF file if they are analyzed, else I consider as non 1/1.001 except if `File_Demux_Rate` option is used for setting a specific 1/1.001 frame rate.
