### ISSUE TITLE
How to tell if a video file is x264 or x265?

### ISSUE THREAD

**Issue by mondocane80** [MediaArea/MediaInfoLib#2122]
How to tell if a video file is x264 or x265?  Some 1080p files are x264 and some are x265 and unless it's written in the video file title itself, there's no way to know.  

Is there a way through your software to determine this?

Thanks

**Comment by JeromeMartinez** [comment]
> How to tell if a video file is x264 or x265?

A video file is never x264 or x265, because x264 and x265 are encoding/decoding tools, not formats.
I guess that you mean H.264 or H.265

So rephrased:

> How to tell if a video file is H.264 or H.265 [...] Is there a way through your software to determine this?

Format line in the Video section, "[AVC](https://en.wikipedia.org/wiki/Advanced_Video_Coding)" is another name for H.264 and "[HEVC](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding)" is another name for H.265.
(and "[VVC](https://en.wikipedia.org/wiki/Versatile_Video_Coding)" is another name for H.266)

**Comment by mondocane80** [comment]
Thanks for the correction.  "x264" or "x265" is sometimes mentioned in the title of the file.  Like for example:

greatmovie.1080p.x264.RABC.mkv

But sometimes the "x264" or "x265" is left out of the title.  That was what I was getting at.

Was not aware of a H.266 and have never encountered a file like that before.  Do they exist?

**Comment by JeromeMartinez** [comment]
> But sometimes the "x264" or "x265" is left out of the title

It means that this was encoded by x264. You have a hint about the encoder name in addition to the format (deduced because e.g. x264 produces only H264 content).

In MediaInfo the encoder name is in its own line (when available, it is not mandatory in a file).

> Was not aware of a H.266 and have never encountered a file like that before. Do they exist?

Yes. Just not (yet, and maybe never due to competition with AV1) a lot spread, as H.265 was not spread during several years after the standard is out.

**Comment by JeromeMartinez** [comment]
> Besides "AVC", "HEVC" or "VVC" is there anything else to look at as far as the video format is concerned?

Each line in MediaInfo is there because it may be useful. Only you can know what your players likes or not.

>  And will those codes always appear for either mp4 and mkv files?

Most containers can have all of them. MKV and MP4 can for sure.
