### ISSUE TITLE
Cannot make a simple example to link

### ISSUE THREAD

**Issue by jcelerier** [MediaArea/MediaInfoLib#485]
I tried: 
```C++
#include <MediaInfo/MediaInfo.h>
#include <iostream>    
int main()
{
  MediaInfoLib::MediaInfo m;
  auto l = m.Option("Info_Parameters");
}
```
with both my distribution's libmediainfo package and a build from source of this repository. In both cases I get : 

    $ g++ test.cpp -lmediainfo
    /tmp/ccl77u6f.o: In function `main':
    test.cpp:(.text+0x56): undefined reference to `MediaInfoLib::MediaInfo::Option(std::string const&, std::string const&)'

**Comment by tribouille** [comment]
Hi,
MediaInfoLib internal strings are unicode...
You need to put your string in unicode:

```C
auto l = m.Option(__T("Info_Parameters"));
```

And compile using UNICODE define:

> g++ test.cpp -lmediainfo -DUNICODE

**Comment by jcelerier** [comment]
thanks, this works.

**Comment by tw-git** [comment]
@tribouille How do you convert a std::string to whatever MediaInfoLib needs? Example from above:
```
#include <MediaInfo/MediaInfo.h>
#include <string>    
int main()
{
  MediaInfoLib::MediaInfo m;
  std::string myString = "Info_Parameters";
  auto l = m.Option(myString); // Won't work
}
```

**Comment by JeromeMartinez** [comment]
the compiled version of MediaInfoLib you have is with wide strings.
So you need std::wstring as input, e.g. `L"Info_Parameters"`.
you can convert between std::string and std::wstring with conversion functions, [example](https://stackoverflow.com/a/18597384/3882655).

Note: we are aware that this is a pain, and we want to change that, but no ETA. `<MediaInfoDLL/MediaInfoDLL.h>`, which loads the .so instead of static link to .so, has support of both std::string and std::wstring.
