### ISSUE TITLE
Display Aspect Ratio wrong in some scenarios due to float number comparison

### ISSUE THREAD

**Issue by Just-Curious** [MediaArea/MediaInfoLib#943]
This was previously reported via email as was the following suggestion for a change in File_Mpeg4_Elements.cpp:
Changing this: 
if (moov_trak_tkhd_DisplayAspectRatio && Height && moov_trak_tkhd_DisplayAspectRatio != ((float32)Width) / Height) 
to this: 
if (moov_trak_tkhd_DisplayAspectRatio && Height && fabs((moov_trak_tkhd_DisplayAspectRatio-((float32)Width)/Height)>0.000001f)) 
[testFiles.zip](https://github.com/MediaArea/MediaInfoLib/files/2281008/testFiles.zip)

Also, I found that building release32 exhibited the problem, but building debug32, release64, or debug64 didn’t. So, I downloaded the standalone release64 and, just like not expected, it exhibited the problem.

**Comment by Just-Curious** [comment]
This error persists in version 18.08.

**Comment by JeromeMartinez** [comment]
Many bugs to fix and I missed this one, but true it would not have taken long for checking that all is OK.

**Comment by Just-Curious** [comment]
This one has not been labeled bug?

**Comment by Just-Curious** [comment]
This error persists in version 18.08.1.  And, not a bug?

**Comment by JeromeMartinez** [comment]
This version was done urgently (bug impacting our sponsors), without checking any other open tickets.
I'll flag as bug when I check if it is a real one.
Note: there is no delay guarantee on free support.

**Comment by Just-Curious** [comment]
As my user name implies, I am truly "just curious".   The issue arose in the Nero forum and it would be them that would benefit.  Hopefully, they contribute to your efforts, but I seriously doubt it!

I do have to compliment you on providing a project that I was able actually build on Windows with very little effort (the GUI being an exception).  So, as indicated elsewhere, I have built it and found the cause of the issue.  It is somewhat baffling to me that there is any question that the code in the description above is not recognized immediately as incorrect.  C'est la vie?

**Comment by JeromeMartinez** [comment]
> It is somewhat baffling to me that there is any question that the code in the description above is not recognized immediately as incorrect.

Last time I wanted to spend "just 5 minutes" on a ticket, I finished to handle it 4 hours later ;-) because it was demonstrating a more bigger issue (the suggested patch was good but showing other bugs so not mergeable without fixing the other bugs at the same time else it would have created more bugs than what was fixed).
It is not always so easy, that's all.

**Comment by Nadahar** [comment]
Just like you're just curious, I'm just observing: It seems to me that you don't quite understand the concept of open source projects like this. When people spend their free time to fix or make things, you can't make demands. Developers can freely choose what they want to address and not, and in my experience there are always many more issues that needs addressing than there available hours. As such, if you want to get somebody to fix "your" issue you must make it as appealing as possible for them to do so. Being condescending does the opposite, it makes it unappealing and might make them pick another task in their free time.

When it comes to the floating point comparison you're correct that it should be compared like you show, but I don't think it's fair (or relevant) to label it a "novice bug". For developers working a lot with floating point it might very well be, but I suspect that many (like myself) only handle (and especially compare) floating points relatively seldom. The "integer handling logic" is so imprinted that it's almost automatic, and thus this can very easily slip by. I for one have to try hard to remember this when dealing with floating points, and I'm pretty sure I've forgotten to do so more often than I've remembered it. You focusing on how "scandalous" it is that this bug exists simply doesn't help at all.

I haven't studied the code so I have no basis to evaluate if this fixes the bug in question, but I assume that it does because it is the correct way to compare floating point numbers. If this is the situation, you have already done most of the job. Why won't you make it easy, and thus appealing, to get this merged by making a PR with that fix? That way it's easy for the project members to review it, build and test it and eventually merge it.

To me it's quite obvious that this approach will have a much higher chance of succeeding, simply because you minimize the work the project members have to do.

**Comment by Just-Curious** [comment]
@nadahar
_I've inserted a few comments into your text before adding additional "information."
Just like you're just curious, I'm just observing: It seems to me that you don't quite understand the concept of open source projects like this When people spend their free time to fix or make things, you can't make demands._ **[I have made no demands.  I have been rather insistent that the 'bug' label should be applied to this issue.]**  _Developers can freely choose what they want to address and not, and in my experience there are always many more issues that needs addressing than there available hours. As such, if you want to get somebody to fix "your"_ **[an?]** _issue you must make it as appealing as possible for them to do so. Being condescending does the opposite, it makes it unappealing and might make them pick another task in their free time._ **["Condescending is "your" word;  I simply reported an issue;  Jerome responded that it would be addressed in "free time" since paying customers have priority;  being curious, as I stated above, I downloaded the source, found some other "interesting" manifestations, found the error, and reported via email; that email was ignored - not even a 'thank you for your efforts']**
_When it comes to the floating point comparison you're correct that it should be compared like you show, but I don't think it's fair (or relevant) to label it a "novice bug"._ **[I would point out that Jerome basically refused to label it a bug at all!]**  _For developers working a lot with floating point it might very well be, but I suspect that many (like myself) only handle (and especially compare) floating points relatively seldom._ **[See below]**.  _The "integer handling logic" is so imprinted that it's almost automatic, and thus this can very easily slip by. I for one have to try hard to remember this when dealing with floating points, and I'm pretty sure I've forgotten to do so more often than I've remembered it. You focusing on how "scandalous" it is that this bug exists simply doesn't help at all._  **[Once again, "scandalous" is your word, not mine!].**
_I haven't studied the code so I have no basis to evaluate if this fixes the bug in question, but I assume that it does because it is the correct way to compare floating point numbers. If this is the situation, you have already done most of the job. Why won't you make it easy, and thus appealing, to get this merged by making a PR with that fix? That way it's easy for the project members to review it, build and test it and eventually merge it._  **[I agree that isolating a line of code that's causing a failure is a major step forward, but I can't agree that I'm the appropriate person to carry on.  I am not familiar with the code which, as you well know, is extensive!]**
_To me it's quite obvious that this approach will have a much higher chance of succeeding, simply because you minimize the work the project members have to do._  **[You do realize that doing that would save 5 minutes?]**
---------------------------------------------------------------------------------------------------------------
I do take your point that not every programmer may have floating point arithmetic at the forefront of their mind.  I'm not even sure that Fortran is still offered as a course?  So, I'll confess to making my own "novice" mistake only yesterday.  Thanks to my daughter, I am now the proud owner of a smart phone.  So, being curious, I bought a book about creating android games using Java.  The last one I built from the provided code had bullets flying around and occasionally disappearing from view.  I attempted to scale down the graphics and "inadvertently" used a copy of a reference in my test code, rather than a copy of the object!  Shame, shame.  Anyway, I discovered my error and then fixed the original code.  I uploaded a recording of it running properly in the Android Studio emulator:  "Bullet Hell" game https://youtu.be/B1ba3rfw9rU

**Comment by JeromeMartinez** [comment]
> that email was ignored - not even a 'thank you for your efforts'

Please stop, I am fully aware that I am not perfect and that I am late on free support including handling bug reports & also [with PRs](https://github.com/MediaArea/MediaInfoLib/pulls). Actually having to read such comments makes me losing time for bug reports and also make me upset, so it delays their fix even more. Please remind that MediaInfo is offered for free, so I don't get money from how many people use it.

BTW:

> I would hope that Nero is among the program's financial supporters.

They don't despite the [availability of a paid support offers](https://mediaarea.net/SupportUs). I they do and consider that this issue is important because their forum users have it in priority, it will move this ticket in paid support list.

***

I already explained that I know I am late, others also tried to explain that nobody owes anything to anyone (BTW thanks @kieranjol & @Nadahar for the support) without paid support agreements, if there is more useless blaming about this obvious facts without constructive proposals about how to have a better MediaInfo global support in practice (which should actually be in another issue ticket with e.g. offer of financial resources or human resources), I'll just lock the ticket.

**Comment by Just-Curious** [comment]
@JeromeMartinez 
Merely flagging this issue as a bug would have avoided all of this and may have resulted in one of those who get to "pick and choose" doing so!  Incidentally, I don't appreciate your so-called supporters beating on me!  Or, your praise of them for doing so.

P.S.  Anyone who spends any time at all on the Nero forum will soon realize that they couldn't care less about their own bugs, let alone anyone else's.

**Comment by Nadahar** [comment]
>  I don't appreciate your so-called supporters beating on me! Or, your praise of them for doing so.

@Just-Curious You've got this all wrong. I am a developer for a different project, which use MediaInfo as one of our dependencies. I'm not a member of anyone's fan club and I certainly didn't intent to "beat on you". I simply tried to help you understand why your approach is (I believe) counter-productive. I'm "on the other side" all the time and have to pick and choose what to deal with and what to postpone. I was merely trying to give you a peek into how "I see the world", and I don't even know if Jerome shares my view.

**Comment by Just-Curious** [comment]
To whom it may concern,

I am going to comply wit Jerome's request and simply stop posting on this issue.  @Nadahar:  I had to Google 'PR'!  Have a good day.

**Comment by JeromeMartinez** [comment]
Thanks for having caught the source of the issue and having suggested a fix, weird because the computing is same (same integer values before doing the computing on float numbers) and I would have expected that compared results are really same, but looks like that it depends on how the compiler optimizes the code.

So I updated the code with your suggested fix (just replacing `0.000001f` by `FLT_EPSILON`) in https://github.com/MediaArea/MediaInfoLib/pull/1086.

**Comment by Just-Curious** [comment]
@Jerome,
You're welcome!
